<?php

namespace AppBundle\Repository;

use AppBundle\Lib\QueryBuilderHelper;
use Doctrine\ORM\QueryBuilder;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $filter
     * @param array $sort
     * @return QueryBuilder
     */
    public function search(array $filter = [], array $sort = []) :QueryBuilder
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.customer', 'c')
            ->leftJoin('s.country', 'l')
            ->leftJoin('s.subscriptions', 'sub')
            ->leftJoin('sub.product', 'p');

        $filter_map = [
            'customer' => ['c.id'],
            'name' => ['s.name'],
            'store' => ['s.id'],
            'country' => ['l.id'],
            'runtime' => ['p.minSubscriptionTime'],
            'recurring' => ['sub.recurring'],
            'search' => ['c.name', 's.name', 's.description', 'l.name']
        ];

        $qb = QueryBuilderHelper::buildFilters($qb, $filter, $filter_map);


        $sort_map = [
            'id' => ['s.id'],
            'name' => ['s.name'],
            'created_at' => ['s.createdAt']
        ];

        $sort_defaults = [
            's.name' => 'ASC'
        ];

        return QueryBuilderHelper::buildSort($qb, $sort, $sort_map, $sort_defaults);
    }
}
