<?php

namespace AppBundle\Repository;

use AppBundle\Lib\QueryBuilderHelper;
use AppBundle\Lib\Tools;
use Doctrine\ORM\QueryBuilder;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $filter
     * @param array $sort
     * @return QueryBuilder
     */
    public function search(array $filter = [], array $sort = []) :QueryBuilder
    {
        $qb = $this->createQueryBuilder('sub')
            ->leftJoin('sub.store', 's')
            ->leftJoin('s.customer', 'c')
            ->leftJoin('sub.product', 'p')
            ->leftJoin('p.item', 'i')
            ->leftJoin('s.country', 'l');

        $filter_map = [
            'subscription' => ['sub.id'],
            'customer' => ['c.id'],
            'name' => ['s.name'],
            'store' => ['s.id'],
            'country' => ['l.id'],
            'runtime' => ['p.minSubscriptionTime'],
            'recurring' => ['sub.recurring'],
            'search' => ['c.name', 's.name', 's.description', 'l.name', 'i.description']
        ];

        $qb = QueryBuilderHelper::buildFilters($qb, $filter, $filter_map);

        // Display the subscription which are currently active
        if (array_key_exists('current', $filter) && !empty($filter['current'])) {
            $month = Tools::getFirstAndLastDayOfMonth(new \DateTime(), 'Y-m-d H:i:s');

            $qb->andWhere($qb->expr()->lte('sub.startDate', ':start'))
                ->andWhere($qb->expr()->gte('sub.endDate', ':end'))
                ->setParameter('start', $month['start_date'])
                ->setParameter('end', $month['end_date']);
        }

        $sort_map = [
            'id' => ['sub.id'],
            'name' => ['s.name'],
            'created_at' => ['sub.createdAt']
        ];

        $sort_defaults = [
            's.name' => 'ASC'
        ];

        return QueryBuilderHelper::buildSort($qb, $sort, $sort_map, $sort_defaults);
    }
}
